# Description:
#   Good band, good band!
#
# Dependencies:
#   None
#
# Configuration:
#   None
#
# Commands:
#   [name of a band] - Good band, good band!
#
# Author:
#   smt

compliment = "Good band, good band!"

bands = [
  "10,000 Maniacs",
  "10000 Maniacs",
  "A Tribe Called Quest",
  "ABC",
  "AC/DC",
  "ACDC",
  "Abba",
  "Aces",
  "Adam & the Ants",
  "Adam and the Ants",
  "Aerosmith",
  "Afghan Whigs",
  "Air",
  "Alice in Chains",
  "Allman Brothers",
  "Aloof",
  "Animals",
  "Aphex Twin",
  "Arrested Development",
  "Asian Dub Foundation",
  "Aztec Camera",
  "B-52's",
  "B-52s",
  "B52's",
  "B52s",
  "Backstreet Boys",
  "Bad Company",
  "Barclay James Harvest",
  "Barenaked Ladies",
  "Basement Jaxx",
  "Beach Boys",
  "Beastie Boys",
  "Beatles",
  "Belle & Sebastian",
  "Belle and Sebastian",
  "Belly",
  "Ben Folds",
  "Big Brother",
  "Big Star",
  "Big Youth",
  "Black Crowes",
  "Black Grape",
  "Black Sabbath",
  "Blind Faith",
  "Blodwyn Pig",
  "Blondie",
  "Blowfish",
  "Blue Nile",
  "Blues Breakers",
  "Blur",
  "Bon Jovi",
  "Bone Thugs",
  "Boo Radleys",
  "Boogie Down Productions",
  "Booker T",
  "Born Jamaicans",
  "Boston",
  "Bounty Killer",
  "Brand New",
  "Bucketheads",
  "Buddy Holly",
  "Buffalo Springfield",
  "Bunny Wailer",
  "Burning Spear",
  "Bush",
  "Byrds",
  "Cake",
  "Canned Heat",
  "Captain Beefheart",
  "Caravan",
  "Carpenters",
  "Cars",
  "Cast",
  "Catatonia",
  "Chameleons",
  "Charlatans",
  "Chemical Bros",
  "Chemical Brothers",
  "Chic",
  "Chicago Transit Authority",
  "Clash",
  "Collective Soul",
  "Colosseum",
  "Commodores",
  "Corrs",
  "Counting Crows",
  "Cranberries",
  "Cream",
  "Creed",
  "Crickets",
  "Crowded House",
  "Cult",
  "Cure",
  "Curve",
  "Cypress Hill",
  "DMB",
  "Damned",
  "Dandy Warhols",
  "Dave Matthews",
  "De la Soul",
  "Dead Kennedys",
  "Deep Purple",
  "Def Leppard",
  "Depeche Mode",
  "Dexys Midnight Runners",
  "Dire Straits",
  "Disposable Heroes of Hiphoprisy",
  "Divine Comedy",
  "Dixie Chicks",
  "Dominos",
  "Doobie Brothers",
  "Doors",
  "Duran Duran",
  "E Street Band",
  "ELO",
  "EPMD",
  "Eagles",
  "Earth Opera",
  "Echo & the Bunnymen",
  "Echo and the Bunnymen",
  "Eels",
  "Electric Flag",
  "Embrace",
  "Eminem",
  "Eurythmics",
  "Eve6",
  "Everclear",
  "Everly Brothers",
  "Everything but the Girl",
  "Fairport Convention",
  "Faith no More",
  "Faithless",
  "Fall",
  "Family",
  "Fleetwood Mac",
  "Flying Burrito Brothers",
  "Foo Fighters",
  "Four Seasons",
  "Four Tops",
  "Frankie Goes to Hollywood",
  "Fugees",
  "Furious Five",
  "Future Sound of London",
  "Garbage",
  "Genesis",
  "Gin Blossoms",
  "GnR",
  "Goldie",
  "Gomez",
  "Goo Goo Dolls",
  "Grateful Dead",
  "Green Day",
  "Guns 'n' Roses",
  "Guns n Roses",
  "Guns â€˜nâ€™ Roses",
  "Haircut 100",
  "Hanson",
  "Happy Mondays",
  "Heart",
  "Heartbreakers",
  "High Tide",
  "Hole",
  "Hollies",
  "Hootie",
  "Hot Tuna",
  "Human League",
  "Husker Du",
  "HÃ¼sker DÃ¼",
  "I Roy",
  "INXS",
  "Iggy",
  "Incredible String Band",
  "Indigo Girls",
  "Iron Butterfly",
  "Iron Maiden",
  "Isley Brothers",
  "Jam",
  "James",
  "Jane's Addiction",
  "Jefferson Airplane",
  "Jefferson Starship",
  "Jellyfish",
  "Jesus & Mary Chain",
  "Jesus and Mary Chain",
  "Jethro Tull",
  "Jewel",
  "Journey",
  "Joy Division",
  "Judas Priest",
  "Jungle Brothers",
  "Kingsmen",
  "Kinks",
  "Kiss",
  "Korn",
  "Kraftwerk",
  "Kula Shaker",
  "La's",
  "Laâ€™s",
  "Leadbelly",
  "Led Zeppelin",
  "Leftfield",
  "Lightning Seeds",
  "Limp Bizkit",
  "Lindisfarne",
  "Little Feat",
  "Living Colour",
  "Lynyrd Skynyrd",
  "MC5",
  "MG's",
  "MGs",
  "Madness",
  "Manic Street Preachers",
  "Marilyn Manson",
  "Massive Attack",
  "Mavericks",
  "Meat Loaf",
  "Meatloaf",
  "Mercury Rev",
  "Metallica",
  "Mighty Diamonds",
  "Moby",
  "Mojos",
  "Monkees",
  "Moody Blues",
  "Mothers of Invention",
  "Motley CrÃ¼e",
  "My Bloody Valentine",
  "NWA",
  "New Order",
  "New Radicals",
  "New Riders of the Purple Sage",
  "New York Dolls",
  "Nine Inch Nails",
  "Nirvana",
  "No Doubt",
  "Oasis",
  "Ocean Colour Scene",
  "Offspring",
  "Orb",
  "PJ Harvey",
  "Panera",
  "Pantera",
  "Pavement",
  "Pearl Jam",
  "Pet Shop Boys",
  "Photek",
  "Pink Floyd",
  "Pixies",
  "Placebo",
  "Plastic Penny",
  "Poco",
  "Pogues",
  "Police",
  "Portishead",
  "Prefab Sprout",
  "Pretenders",
  "Pretty Things",
  "Primal Scream",
  "Prince",
  "Prodigy",
  "Public Enemy",
  "Puff Daddy & the Family",
  "Puff Daddy and the Family",
  "Pulp",
  "Queen",
  "REM",
  "Radiohead",
  "Rage Against the Machine",
  "Ramones",
  "Raspberries",
  "Red Hot Chili Peppers",
  "Red Snapper",
  "Replacements",
  "Rhinoceros",
  "Rob Zombie",
  "Rolling Stones",
  "Roxy Music",
  "Run DMC",
  "Rush",
  "Santana",
  "Savage Garden",
  "Scarlet Party",
  "Sex Pistols",
  "Shadows",
  "Simon & Garfunkel",
  "Simon and Garfunkel",
  "Simple Minds",
  "Simply Red",
  "Siouxsie & the Banshees",
  "Siouxsie and the Banshees",
  "Sly & the Family Stone",
  "Sly and the Family Stone",
  "Small Faces",
  "Smashing Pumpkins",
  "Smithereens",
  "Smiths",
  "Soft Machine",
  "Sonic Youth",
  "Soul II Soul",
  "Soundgarden",
  "Spice Girls",
  "Spirit",
  "Spiritualized",
  "Spooky Tooth",
  "Springsteen",
  "Squeeze",
  "Starry Eyed & Laughing",
  "Starry Eyed and Laughing",
  "Stealers Wheel",
  "Steely Dan",
  "Stereolab",
  "Stereophonics",
  "Sting",
  "Stone Roses",
  "Stone Temple Pilots",
  "Stooges",
  "Stooges",
  "Stranglers",
  "Strawberry Alarm Clock",
  "Style Council",
  "Styx",
  "Sublime",
  "Suede",
  "Sugar",
  "Summercamp",
  "Sun Ra",
  "Sundays",
  "Supergrass",
  "Supertramp",
  "Supremes",
  "Swinging Blue Jeans",
  "T Rex",
  "TLC",
  "Taj Mahal",
  "Talk Talk",
  "Talking Heads",
  "Tangerine Dream",
  "Tears for Fears",
  "Technotronic",
  "Teenage Fanclub",
  "Television",
  "Temptations",
  "Texas",
  "They Might be Giants",
  "Thin Lizzy",
  "Third Eye Blind",
  "Tom Petty",
  "Tool",
  "Toots & the Maytals",
  "Toots and the Maytals",
  "Traffic",
  "Travis",
  "Tribe Called Quest",
  "U2",
  "UB40",
  "Underworld",
  "Upsetters",
  "Van Halen",
  "Various Artists",
  "Velvet Underground",
  "Verve",
  "Violent Femmes",
  "Wailers",
  "Weather Report",
  "Wilco",
  "Wings",
  "Wire",
  "World Party",
  "Wu Tang",
  "XTC",
  "Yellowman",
  "Youngbloods",
  "ZZ Top",
  "Zappa",
  "Zombies"
].join('|')

pattern = new RegExp '\\b(' + bands + ')\\b', 'i'

module.exports = (robot) ->
  robot.hear pattern, (msg) ->
    msg.send compliment
